from __future__ import annotations
from typing import Any

# This module defines low-level conversion helpers used by convert.py.
# Exact signatures depend on your installed version;
# these stubs keep Pylance happy by typing them as callable helpers.

def get_greta_from_date(date: Any) -> str: ...
def get_date_from_greta(greta: Any) -> str: ...
def get_jd_from_date(date: Any) -> float: ...
def get_date_from_jd(jd: Any) -> str: ...
def get_maude_from_date(date: Any) -> int: ...
def get_date_from_maude(maude: Any) -> str: ...

# Add additional helpers as needed.
