from __future__ import annotations
from typing import Union
from datetime import datetime
from .cxotime import CxoTimeLike

# All converters accept str | float | int | datetime | CxoTime, etc.
Scalar = Union[str, float, int, datetime, CxoTimeLike]

def convert(value: Scalar, in_format: str, out_format: str) -> Scalar: ...
def convert_time_format(value: Scalar, in_format: str, out_format: str) -> Scalar: ...

def date2secs(date: Scalar) -> float: ...
def secs2date(secs: Scalar) -> str: ...

def date2jd(date: Scalar) -> float: ...
def jd2date(jd: Scalar) -> str: ...

def date2greta(date: Scalar) -> str: ...
def greta2date(greta: Scalar) -> str: ...

def date2maude(date: Scalar) -> int: ...
def maude2date(maude: Scalar) -> str: ...

def secs2jd(secs: Scalar) -> float: ...
def jd2secs(jd: Scalar) -> float: ...

def secs2greta(secs: Scalar) -> str: ...
def greta2secs(greta: Scalar) -> float: ...

def secs2maude(secs: Scalar) -> int: ...
def maude2secs(maude: Scalar) -> float: ...

def greta2jd(greta: Scalar) -> float: ...
def jd2greta(jd: Scalar) -> str: ...

def greta2maude(greta: Scalar) -> int: ...
def maude2greta(maude: Scalar) -> str: ...

def maude2jd(maude: Scalar) -> float: ...
def jd2maude(jd: Scalar) -> int: ...

def print_time_conversions(value: Scalar) -> None: ...
